/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import locationPlugin from "@notum-cz/strapi-plugin-location/strapi-admin";
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import customDashboard from "../../src/plugins/custom-dashboard/strapi-admin";
import theatreSearch from "../../src/plugins/theatre-search/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.js";

renderAdmin(document.getElementById("strapi"), {
  customisations,

  plugins: {
    "location-plugin": locationPlugin,
    "strapi-cloud": strapiCloud,
    i18n: i18N,
    "users-permissions": usersPermissions,
    "custom-dashboard": customDashboard,
    "theatre-search": theatreSearch,
  },
});
